package org.jeyzer.gradle;

/*-
 * ---------------------------LICENSE_START---------------------------
 * Jeyzer Profile Updater Maven Plugin
 * --
 * Copyright (C) 2020 Jeyzer SAS
 * --
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * ----------------------------LICENSE_END----------------------------
 */

import java.io.File;

import org.gradle.api.DefaultTask;
import org.gradle.api.tasks.TaskAction;
import org.gradle.api.tasks.TaskExecutionException;

import org.jeyzer.profile.JeyzerProfileUpdater;
import org.jeyzer.profile.error.InvalidPatternsException;
import org.jeyzer.profile.error.ProfileUpdaterInitException;

public class JeyzerProfileUpdaterTask extends DefaultTask{

	private final String DESCRIPTION = "Updates the Jeyzer 'sourcePatterns' with the 'newPatternEntries' generated by the java build of the Jeyzer annotations. Resulting patterns are stored in the 'targetPatternsDir'/'targetPatternsName.xml'";
	
    @TaskAction
    public void updateProfile() throws TaskExecutionException {
    	this.setDescription(DESCRIPTION);
    	
    	JeyzerProfileUpdaterPluginExtension extension = getProject().getExtensions().findByType(JeyzerProfileUpdaterPluginExtension.class);

    	extension= completeExtension(extension);

    	JeyzerProfileUpdater updater = new JeyzerProfileUpdater();
    	
    	File profileTargetDir = new File(extension.getTargetPatternsDir());
    	if (profileTargetDir.exists() && profileTargetDir.isFile())
    		throw new TaskExecutionException (this, new Exception("Patterns target directory is a file. Please check the profile updater parameters. Given directory path is : " + extension.getTargetPatternsDir()));

    	if (!profileTargetDir.exists()) {
    		boolean result = profileTargetDir.mkdirs();
    		if (!result)
        		throw new TaskExecutionException (this, new Exception("Patterns target directory creation failed. Given directory path is : " + extension.getTargetPatternsDir()));
    	}
    	
    	File profileTarget = new File(
    			extension.getTargetPatternsDir(), 
    			extension.getTargetPatternsName() + ".xml"
    			);
    	File sourceProfile = new File(
    			extension.getSourcePatterns()
    			);
    	File newProfileEntries = new File(
    			extension.getNewPatternEntries()
    			);
    	
    	getLogger().info("Generating patterns    : " + profileTarget.getPath());
    	getLogger().info("  from source patterns : " + sourceProfile.getPath());
    	getLogger().info("  with entries from   : " + newProfileEntries.getPath());
    	
    	try {
			updater.execute(
					sourceProfile, 
					profileTarget, 
					newProfileEntries
					);
		} catch (InvalidPatternsException ex) {
			throw new TaskExecutionException (this, ex);
		} catch (ProfileUpdaterInitException ex) {
			throw new TaskExecutionException (this, ex);
		} catch (Exception ex) {
			throw new TaskExecutionException (this, ex);
		}
    }

	private JeyzerProfileUpdaterPluginExtension completeExtension(JeyzerProfileUpdaterPluginExtension extension) {
		if(extension == null)
			extension = new JeyzerProfileUpdaterPluginExtension();
		
    	String name = getProject().getName();
    	
    	if (extension.getSourcePatterns() == null){
        	String defaultSourceProfile = getProject().getProjectDir() 
            		+ "/src/main/config/jeyzer/" + name + "/" + name + "_patterns.xml";
            extension.setSourcePatterns(defaultSourceProfile);    		
    	}
        
    	if (extension.getNewPatternEntries() == null){
        	String defaultNewProfileEntries = getProject().getBuildDir() 
            		+ "/generated-sources/jeyzer/new_pattern_entries.xml";
            extension.setNewPatternEntries(defaultNewProfileEntries);    		
    	}
    	
    	if (extension.getTargetPatternsDir() == null){
        	String defaultTargetProfileDir = getProject().getBuildDir() 
            		+ "/generated-sources/jeyzer";
            extension.setTargetPatternsDir(defaultTargetProfileDir);    		
    	}
    	
    	if (extension.getTargetPatternsName() == null){
        	String defaultTargetProfileName = name + "_patterns";
            extension.setTargetPatternsName(defaultTargetProfileName);    		
    	}
        
		return extension;
	}
	
}
